In [14]:
import requests
import json

import pandas as pd

In [32]:
def get_symbols(country):

    headers = {
        "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Referer": "https://www.tradingview.com/",
        "Origin": "https://www.tradingview.com",
        "Connection": "keep-alive",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site",
        "Priority": "u=4",
    }

    symbols_remaining = 50
    start = 0
    all_symbols = []

    while symbols_remaining > 0:

        url = f'https://symbol-search.tradingview.com/symbol_search/v3/?text=&hl=1&country={country}&lang=en&search_type=stocks&start={start}&domain=production&sort_by_country={country}'

        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            data = response.json()
        else:
            print(f"Request failed with status code {response.status_code}")
            print(response.text)

        symbols_remaining = data['symbols_remaining']

        print(symbols_remaining)

        all_symbols += data['symbols']
        start = len(all_symbols)

    return all_symbols

def symbols_to_df(symbols_dict):
    df = pd.DataFrame(symbols_dict)
    df.drop(columns=['currency-logoid', 'logoid', 'provider_id', 'source2', 'source_id', 'typespecs', 'prefix'], errors='ignore', inplace=True)
    return df

In [ ]:
us_symbols = get_symbols("US")

In [26]:
display(us_symbols[0])

us_df = symbols_to_df(us_symbols)
display(us_df.head())

us_df.to_csv('us_symbols.csv', index=False)

{'symbol': 'NVDA',
 'description': 'NVIDIA Corporation',
 'type': 'stock',
 'exchange': 'NASDAQ',
 'currency_code': 'USD',
 'currency-logoid': 'country/US',
 'logoid': 'nvidia',
 'provider_id': 'ice',
 'source2': {'id': 'NASDAQ',
  'name': 'Nasdaq Stock Market',
  'description': 'Nasdaq Stock Market'},
 'source_id': 'NASDAQ',
 'country': 'US',
 'is_primary_listing': True,
 'typespecs': ['common']}

,symbol,description,type,exchange,currency_code,country,is_primary_listing
0,NVDA,NVIDIA Corporation,stock,NASDAQ,USD,US,True
1,TSLA,"Tesla, Inc.",stock,NASDAQ,USD,US,True
2,AAPL,Apple Inc.,stock,NASDAQ,USD,US,True
3,AMZN,"Amazon.com, Inc.",stock,NASDAQ,USD,US,True
4,PLTR,Palantir Technologies Inc.,stock,NASDAQ,USD,US,True

In [28]:
uk_symbols = get_symbols("GB")

8815
8765
8715
8665
8615
8565
8515
8465
8415
8365
8315
8265
8215
8165
8115
8065
8015
7965
7915
7865
7815
7765
7715
7665
7615
7565
7515
7465
7415
7365
7315
7265
7215
7165
7115
7065
7015
6965
6915
6865
6815
6765
6715
6665
6615
6565
6515
6465
6415
6365
6315
6265
6215
6165
6115
6065
6015
5965
5915
5865
5815
5765
5715
5665
5615
5565
5515
5465
5415
5365
5315
5265
5215
5165
5115
5065
5015
4965
4915
4865
4815
4765
4715
4665
4615
4565
4515
4465
4415
4365
4315
4265
4215
4165
4115
4065
4015
3965
3915
3865
3815
3765
3715
3665
3615
3565
3515
3465
3415
3365
3315
3265
3215
3165
3115
3065
3015
2965
2915
2865
2815
2765
2715
2665
2615
2565
2515
2465
2415
2365
2315
2265
2215
2165
2115
2065
2015
1965
1915
1865
1815
1765
1715
1665
1615
1565
1515
1465
1415
1365
1315
1265
1215
1165
1115
1065
1015
965
915
865
815
765
715
665
615
565
515
465
415
365
315
265
215
165
115
65
15
0

In [33]:
display(uk_symbols[0])

uk_df = symbols_to_df(uk_symbols)
display(uk_df.head())

uk_df.to_csv('uk_symbols.csv', index=False)

{'symbol': '01QC',
 'description': "RESIDENTIAL MORTGAGE SECURITIES 10 RESIDUAL CERTS 8/2039 REG'S'",
 'type': 'structured',
 'exchange': 'LSE',
 'currency_code': 'GBP',
 'currency-logoid': 'country/GB',
 'provider_id': 'ice',
 'source2': {'id': 'LSE',
  'name': 'London Stock Exchange',
  'description': 'London Stock Exchange'},
 'source_id': 'LSE',
 'country': 'GB',
 'typespecs': ['etn']}

,symbol,description,type,exchange,currency_code,country,is_primary_listing
0,01QC,RESIDENTIAL MORTGAGE SECURITIES 10 RESIDUAL CE...,structured,LSE,GBP,GB,NaN
1,05IS,MANDO MACHINERY CORP GDR EACH REPR 1/2 SHS COM...,dr,LSE,USD,GB,NaN
2,09II,DR. ING. H.C. F. PORSCHE AG NON-VTG PRF NPV,stock,LSIN,EUR,GB,NaN
3,09OE,MERRILL LYNCH INTERNATIONAL & CO CV CALLWTS RE...,structured,LSE,USD,GB,NaN
4,0A00,AKZO NOBEL NV EUR0.50(POST REV SPLIT),stock,LSIN,EUR,GB,NaN